import '@/styles/globals.css'
import type { Metadata } from 'next'

import Footer from '@/components/layouts/Footer'
import Header from '@/components/layouts/Header'
import { ThemeProvider } from '@/components/theme-provider'
import { Alexandria, Josefin_Sans } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { cn } from '@/lib/utils'

const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap'
})
const alexandria = Alexandria({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'My Github Profile',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const messages = await getMessages()
  const lacale = await getLocale()
  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={lacale} dir={lacale === 'ar' ? 'rtl' : 'ltr'}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <body
            className={cn(
              'container flex h-screen max-h-screen min-h-screen flex-col bg-background text-foreground',
              lacale === 'ar' ? alexandria.className : josefin.className
            )}
          >
            <Header />

            <main className='flex-1'>{children}</main>

            <Footer />
          </body>
        </ThemeProvider>
      </html>
    </NextIntlClientProvider>
  )
}
